name: DevOps Team - Auto PR Approval

on:
  pull_request_target:
    types: [opened, ready_for_review, reopened, synchronize]
  pull_request_review:
    types: [dismissed]

run-name: "DevOps Team - Auto PR Approval"

jobs:
  workflow-call:
    name: ⚙️ Job
    uses: Novibet/devops.repofilesync/.github/workflows/sw-devops-auto-approval.yml@latest
    secrets: inherit
